Repository CS2103-AY1819S2-W14-2/main, pull requests merged in 2019-03, with the labels that each got.

#10 Add import command and accompanying UI component.
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/Notifier.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/image/Image.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/ImagePanel.java
  src/main/java/seedu/address/ui/InformationPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/assets/sample.png
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/ImagePanel.fxml
  src/main/resources/view/InformationPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, type.Epic

#22 Added Open Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/resources/assets/sample2.jpg
Labels: priority.High

#27 Refactor import
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/RotateCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/assets/sample2.jpg
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Low

#36 ListFiles Command Implemented
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/ListFilesCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/assets/sample2.png
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#34 Edited user story
  docs/DeveloperGuide.adoc
Labels: type.Story

#38 Refactoring some parts
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ListFilesCommand.java
  src/main/java/seedu/address/logic/commands/RotateCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/image/Image.java
  src/main/java/seedu/address/ui/ImagePanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task

#39 Implement Contrast Command
  build.gradle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ContrastCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ContrastCommandParser.java
  src/main/java/seedu/address/model/image/Image.java
  src/main/resources/assets/sampleContrast.jpg
Labels: status.Ongoing

#58 Developer Guide updates for Open and User Guide Updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#68 Save Function Implemented
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/image/Image.java
  src/main/resources/assets/ContrastCommandDiagram.png
  src/main/resources/assets/sample.png
  src/main/resources/assets/sample2.png
  src/main/resources/temp/sample.png
  src/main/resources/temp/sampleBrightness.jpg
  src/main/resources/temp/sampleContrast.jpg
  src/main/resources/temp/temp_img
  src/main/resources/temp/temp_img.png
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#72 Bug fix for Open and Save Functions
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/assets/sample.png
  src/main/resources/temp/temp_img.png
Labels: severity.High, status.Ongoing, type.Bug, type.Task

#92 Refactored listfiles, open and save. Changed icon and name of app.
  src/main/java/seedu/address/logic/commands/ListFilesCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/model/CurrentEdit.java
  src/main/java/seedu/address/model/CurrentEditManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/assets/66127a9bdf5c5f62402331976c0d9f7e.jpg
  src/main/resources/assets/sample.png
  src/main/resources/assets/sample2.png
  src/main/resources/images/address_book_32.png
  src/main/resources/images/fomofoto_icon.png
  src/main/resources/temp/sample.png
  src/main/resources/temp/temp_img.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  z
Labels: priority.High, severity.High

#98 Fix bug for Save
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/model/CurrentEdit.java
  src/main/java/seedu/address/model/CurrentEditManager.java
  src/main/resources/temp/sample.png
  src/main/resources/temp/temp_img.png
Labels: priority.High, severity.High, type.Bug

#126 Refactor methods to Album class
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelComponents.png
  src/main/java/seedu/address/logic/commands/ListFilesCommand.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/main/java/seedu/address/model/Album.java
  src/main/java/seedu/address/model/CurrentEdit.java
  src/main/java/seedu/address/model/CurrentEditManager.java
  src/main/resources/assets/sample.png
  src/test/imageTest/sample.png
Labels: priority.High, status.Ongoing, type.Task
